# Generated by Django 6.1 on 2026-08-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtos', models.CharField(max_length=299)),
                ('data_de_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
